version: '3',
services:
  web:
    build: .
    command: npm start
    ports: 
    - "3000:3000"
    volumes:
    - .:/usr/src/app
    - logvolume01:/var/log
    links:
    - redis
  worker:
    build: .
    command: npm run task
    volumes:
    - .:/usr/src/app
    links:
      - redis
  redis:
    image: redis
volumes:
  logvolume01: {}