version: '3',
services:
  web:
    build: .
    ports: 
    - "5000:5000"
    volumes:
    - .:/usr/src/app
    - logvolume01:/var/log
    links:
    - redis
  worker:
    build: .
    volumes:
    - .:/usr/src/app
    links:
      - redis
  redis:
    image: redis
volumes:
  logvolume01: {}